# --- PostgreSQL DB Config ---
spring.datasource.url=jdbc:postgresql://localhost:5432/hospital_db
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}

# --- JPA / Hibernate ---
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true

# Disable SQL debug logs completely
spring.jpa.show-sql=false
logging.level.org.hibernate.SQL=off
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=off
logging.level.org.hibernate.orm.jdbc.bind=off

# --- Server Port ---
server.port=8080
